spring:
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:mysql://localhost:3306/festival_gourmet
    username: ${USUARIO_BASE_DATOS}
    password: ${CONTRASENA_BASE_DATOS}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  thymeleaf:
    cache: false